# Generated by Django 3.1.6 on 2021-02-09 22:36

from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=50, verbose_name='Razão Social')),
                ('cnpj', localflavor.br.models.BRCNPJField(max_length=18, verbose_name='CNPJ')),
                ('end_cep', localflavor.br.models.BRPostalCodeField(max_length=9, verbose_name='CEP')),
                ('end_logradouro', models.CharField(max_length=250, verbose_name='Logradouro')),
                ('end_numero', models.CharField(max_length=50, verbose_name='Número')),
                ('end_bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('telefone', models.CharField(max_length=50, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto', models.TextField(verbose_name='Objeto')),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'Empréstimos'), (2, 'Arrendamento'), (3, 'Seguro'), (4, 'Locação de Serviços'), (5, 'Equipamentos')], verbose_name='tipo')),
                ('carencia', models.BooleanField(verbose_name='Carência')),
                ('dt_inicio_vigencia', models.DateField(verbose_name='Dt. Inicio Vigência')),
                ('dt_fim_vigencia', models.DateField(verbose_name='Dt. Fim Vigência')),
                ('status', models.CharField(choices=[('E', 'Em Edição'), ('A', 'Ativo'), ('C', 'Cancelado')], default='E', max_length=1, verbose_name='Status')),
                ('valores', models.TextField(verbose_name='Valores')),
                ('prazos', models.TextField(verbose_name='Prazos')),
                ('contratada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresa_contratada', to='contratos.empresa', verbose_name='Contratada')),
                ('contratante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresa_contratante', to='contratos.empresa', verbose_name='Contratante')),
            ],
            options={
                'verbose_name': 'contrato',
                'verbose_name_plural': 'contratos',
            },
        ),
    ]
